export const codeLanguages = [
    {lang:"html", title:"HTML"},
    {lang:"css", title:"CSS"},
    {lang:"sass", title:"SASS"},
    {lang:"scss", title:"SCSS"},
    {lang:"bash", title:"Bash"},
    {lang:"c", title:"C"},
    {lang:"csharp", title:"C#"},
    {lang:"C", title:"C++"},
    {lang:"dart", title:"Dart"},
    {lang:"docker", title:"Docker"},
    {lang:"go", title:"Go"},
    {lang:"java", title:"Java"},
    {lang:"javascript", title:"JavaScript"},
    {lang:"json", title:"Json"},
    {lang:"jsx", title:"JSX"},
    {lang:"php", title:"PHP"},
    {lang:"python", title:"Python"},
    {lang:"r", title:"R"},
    {lang:"ruby", title:"Ruby"},
    {lang:"rust", title:"Rust"},
    {lang:"sql", title:"SQL"},
    {lang:"swift", title:"Swift"},
    {lang:"typescript", title:"TypeScript"},
    // {lang:"markup", title:"Markup"},
    // {lang:"nginx", title:"NGINX"},
    // {lang:"apacheconf", title:"Apache"},
    // {lang:"graphql", title:"GraphQL"},
    // {lang:"plsql", title:"PostgreSQL"},
];